ParadoxGameConverters/EU4ToVic2

- EU4toV2/Source/EU4World/Regions/Region.cpp
> Handle the last region parse error.

- EU4toV2/Data_Files/blankMod/output/common/cultures.txt
- EU4toV2/Data_Files/blankMod/output/decisions/converterUnions.txt
- EU4toV2/Data_Files/blankMod/output/history/pops/1836.1.1/Belize.txt
- EU4toV2/Data_Files/blankMod/output/history/pops/1836.1.1/Burma.txt
- EU4toV2/Data_Files/blankMod/output/history/pops/1836.1.1/Ceylon.txt
- EU4toV2/Data_Files/blankMod/output/history/pops/1836.1.1/Gibraltar.txt
- EU4toV2/Data_Files/blankMod/output/history/pops/1836.1.1/Greece.txt
- EU4toV2/Data_Files/blankMod/output/history/pops/1836.1.1/India.txt
- EU4toV2/Data_Files/blankMod/output/history/pops/1836.1.1/Ireland.txt
- EU4toV2/Data_Files/blankMod/output/history/pops/1836.1.1/Malaysia.txt
- EU4toV2/Data_Files/blankMod/output/history/pops/1836.1.1/Malta.txt
- EU4toV2/Source/V2World/V2Country.cpp
The fallback "British" culture should now no longer appear.
> Removal of fallback "British" culture

- EU4toV2/Data_Files/blankMod/output/decisions/converterPostCol.txt
This should make it impossible for a post-colonial country to simply spam decisions to get free prestige, switching from Cuba to Jamaica indefinitly.
> Further check to post-colonial countries

- .clang-format
Adds a clang-format file to the base directory, so devs don't have to format manually.
> Add clang-format file with indentation and brace style

- EU4toV2/Source/EU4World/Provinces/EU4Province.cpp
- EU4toV2/Source/EU4World/Provinces/EU4Province.h
- EU4toV2/Source/V2World/V2Province.cpp
- EU4toV2/Source/V2World/V2Province.h
Ignore old rules for determining colonial status and use EU4 territorial cores.
> Creating territories according to EU4 territorial cores

- EU4ToVic2Tests/ConfigurationTests.cpp
- EU4toV2/Data_Files/Eu4ToVic2DefaultConfiguration.xml
- EU4toV2/Data_Files/configuration.txt
- EU4toV2/Source/Configuration.cpp
- EU4toV2/Source/Configuration.h
- EU4toV2/Source/EU4World/EU4Country.cpp
- EU4toV2/Source/EU4World/Provinces/EU4Province.cpp
- EU4toV2/Source/EU4World/Provinces/EU4Province.h
- EU4toV2/Source/EU4World/Provinces/ProvinceHistory.cpp
- EU4toV2/Source/EU4World/Provinces/ProvinceHistory.h
- EU4toV2/Source/V2World/V2Province.cpp
- EU4toV2/Source/V2World/V2Province.h
- EU4toV2/Source/V2World/V2World.cpp
Introducing boosts and penalties to Vic2 vanilla populations based on life rating, dev pushes over EU4 timeframe and overall province weight. 
Altering frontend input fields to reflect changes.
Adjusted frontend tests.
> Popshaping

- EU4toV2/Source/V2World/V2Province.cpp
Colony in progress converts to actual colony now.
> fix for #320

- EU4toV2/Data_Files/blankMod/output/common/bookmarks.txt
- EU4toV2/Data_Files/blankMod/output/common/defines.lua
- EU4toV2/Data_Files/country_mappings.txt
- EU4toV2/Source/Configuration.h
- EU4toV2/Source/EU4World/Provinces/PopRatio.cpp
- EU4toV2/Source/EU4World/Provinces/ProvinceHistory.cpp
- EU4toV2/Source/EU4World/World.cpp
- EU4toV2/Source/V2World/V2Country.cpp
- EU4toV2/Source/V2World/V2World.cpp
- Issue #166 - floating start date according to savegame date
- fixed crash with factory distribution when everyone is civilized (most often when converting a 1444 save, or earlier with mods)
- capped culture/religion conversions for long games (over 400 years)
- capped culture/religion conversions at actual end date instead of 1821.
- swapped d_anjou for ANJ (see issue #323)
> Floating Vic2 bookmark

- EU4toV2/Data_Files/configuration.txt
- EU4toV2/Source/EU4World/EU4Country.cpp
- EU4toV2/Source/V2World/V2Country.h
- EU4toV2/Source/V2World/V2World.cpp
- EU4toV2/Source/V2World/V2World.h
- zeroes prestige on vassals
- correctly vassalizes unions
- marches no longer absorbed but vassalized
> Diplomacy patch

- EU4toV2/Source/EU4World/World.cpp
> Fix for ironman recognition

- EU4toV2/Data_Files/governmentMapping.txt
- EU4toV2/Data_Files/minorityPops.txt
- EU4toV2/Data_Files/partyNames.txt
- EU4toV2/Data_Files/reform_effects.txt
- EU4toV2/EU4ToV2.vcxproj
- EU4toV2/EU4ToV2.vcxproj.filters
- EU4toV2/Source/EU4World/Country/EU4CustomColors.h
- EU4toV2/Source/FlagUtils.cpp
- EU4toV2/Source/FlagUtils.h
- EU4toV2/Source/Mappers/FlagColorMapper.cpp
- EU4toV2/Source/Mappers/FlagColorMapper.h
- EU4toV2/Source/Mappers/GovermentMapper.cpp
- EU4toV2/Source/Mappers/GovernmentMapper.h
- EU4toV2/Source/Mappers/MinorityPop.cpp
- EU4toV2/Source/Mappers/MinorityPop.h
- EU4toV2/Source/Mappers/MinorityPopMapper.cpp
- EU4toV2/Source/Mappers/MinorityPopMapper.h
- EU4toV2/Source/V2World/V2Country.cpp
- EU4toV2/Source/V2World/V2Country.h
- EU4toV2/Source/V2World/V2Flags.cpp
- EU4toV2/Source/V2World/V2Flags.h
- EU4toV2/Source/V2World/V2World.cpp
- EU4toV2/Source/V2World/V2World.h
- EU4toV2/Source/main.cpp
- governmentMapper
- minorityPopMapper
- flagColorMapper
Related files patched accordingly.
> Mapper rewrites

- EU4toV2/Source/EU4World/Country/EU4Country.cpp
- EU4toV2/Source/EU4World/Country/EU4Country.h
- EU4toV2/Source/Mappers/Pops/MapperPop.cpp
- EU4toV2/Source/V2World/Country/Country.cpp
- EU4toV2/Source/V2World/Country/Country.h
- EU4toV2/Source/V2World/Country/CountryDetails.cpp
- EU4toV2/Source/V2World/Country/CountryDetails.h
- EU4toV2/Source/V2World/Output/outCountry.cpp
Starting consciousness is generated from legitimacy (and its equivalents for non-monarchies) and stability at the point of conversion.
> Starting consciousness - fix for #70

- EU4toV2/Data_Files/configurables/ck2_title_map.txt
- EU4toV2/Data_Files/configurables/version.txt
- EU4toV2/Data_Files/configuration.txt
- EU4toV2/Source/Mappers/CK2Titles/TitleMapping.cpp
- EU4toV2/Source/Mappers/ColonialFlags/ColonialFlag.cpp
- updated default config.txt
- converted ck2_titles to ansi so we don't need utf8 converter (titles are ansi by default in source files anyway)
- dropped excess converters
> Text updates

- EU4toV2/Source/EU4World/Country/EU4Country.cpp
- EU4toV2/Source/EU4World/World.cpp
We were missing accepted cultures because we calced them before building popratios.
> Fix for missing accepted cultures.

- EU4toV2/Data_Files/configurables/country_mappings.txt
- EU4toV2/Source/EU4World/Country/EU4Country.cpp
- EU4toV2/Source/EU4World/Country/EU4Country.h
- EU4toV2/Source/EU4World/Country/EU4CountryFlags.cpp
- EU4toV2/Source/Mappers/CountryMappings/CountryMapping.cpp
- EU4toV2/Source/Mappers/CountryMappings/CountryMapping.h
- EU4toV2/Source/Mappers/CountryMappings/CountryMappings.cpp
- EU4toV2/Source/Mappers/CountryMappings/CountryMappings.h
> Adding reforms and flags to country mapping.

- EU4toV2/Data_Files/configurables/ck2_title_map.txt
- EU4toV2/Data_Files/configurables/colonial_tags.txt
- EU4toV2/Source/Mappers/CountryMappings/CountryMappings.cpp
- EU4toV2/Source/Mappers/CountryMappings/CountryMappings.h
- EU4toV2/Source/V2World/Flags/Flags.cpp
- don't flaggify flagful colonials in the first place
- if flaggifying flagless colonials, flaggify thosethat are flagless instead of noone thank you.
- alaska is not a ck2 region under any circumstance.
> Fixing colonial flag algorithm a bit.

- EU4toV2/Data_Files/Eu4ToVic2DefaultConfiguration.xml
- EU4toV2/Source/Configuration.cpp
- EU4toV2/Source/Configuration.h
- EU4toV2/Source/V2World/V2World.cpp
> Output_name from converter frontend

- EU4toV2/Source/V2World/Diplomacy/Diplomacy.cpp
- EU4toV2/Source/V2World/Flags/Flags.cpp
- this caused flags to think there was an overlord colonial flag situation.
> Dropping diplo agreements for absorbed nations

- EU4toV2/Source/V2World/Flags/Flags.cpp
- not so much missing as unsaved.
> Fixing missing overlord for premade flag owners.

- EU4toV2/Data_Files/configurables/starting_technologies.txt
We were assigning stock market but forgot to assign preceding technology.
> Adding missing banks

- EU4toV2/Source/V2World/Diplomacy/Diplomacy.cpp
We were deleting agreements in a broken fashion, and for no reason.
> Fixing colony absorption

- EU4toV2/Source/V2World/Country/Country.cpp
> Fixing uncivs at westernization 10

- EU4toV2/Data_Files/blankMod/output/events/Olympics.txt
- EU4toV2/Source/V2World/Output/outCultureGroups.cpp
Disabling olympics for weird tags
Disabling FromUTF8 conversion on incoming culture files.
> Olympics and name diacritics.

- EU4toV2/Data_Files/configurables/province_mappings.txt
Fixing a couple persian mappings.
> Persian mappings

- EU4toV2/Data_Files/configurables/culture_map.txt
- EU4toV2/Data_Files/configurables/culture_map_slaves.txt
- EU4toV2/Data_Files/configurables/tech_groups.txt
- EU4toV2/Source/Mappers/CultureMapper/CultureMapper.cpp
- EU4toV2/Source/Mappers/CultureMapper/CultureMapper.h
- EU4toV2/Source/Mappers/CultureMapper/CultureMappingRule.h
- EU4toV2/Source/Mappers/TechGroups/TechGroups.cpp
- EU4toV2/Source/Mappers/TechGroups/TechGroups.h
- EU4toV2/Source/Mappers/TechGroups/TechGroupsMapper.cpp
- EU4toV2/Source/Mappers/TechGroups/TechGroupsMapper.h
- EU4toV2/Source/V2World/Country/Country.cpp
- EU4toV2/Source/V2World/Country/Country.h
- EU4toV2/Source/V2World/Country/CountryDetails.cpp
- EU4toV2/Source/V2World/State/State.cpp
- EU4toV2/Source/V2World/State/State.h
- EU4toV2/Source/V2World/V2World.cpp
- EU4toV2/Source/V2World/V2World.h
- Culture maps compressed and cleaned
- Cultures given westernization score according to tech group.
- Civilized peoples will always be states for civilized countries.
- Uncivilized peoples wil be territories for civilized countries
- Any people will be states for uncivilized countries.
- Lots of clang.
> States rework and major culture cleanup.

- EU4toV2/Data_Files/blankMod/output/events/TheRaj.txt
Indian Raj won't exist anymore
> Indian Raj Fix

- EU4toV2/Data_Files/configurables/culture_map.txt
Also religionals come after regionals but before globals.
> Reordering cultures so regionals always come before globals.

- EU4toV2/Source/V2World/Province/Province.cpp
- EU4toV2/Source/V2World/V2World.cpp
Fixing paths for recursive province scrape.
> Updating commons

- EU4ToVic2Tests/MapperTests/CountryFlagsMapperTests.cpp
- EU4toV2/Data_Files/configurables/province_mappings.txt
- EU4toV2/Source/Mappers/CountryFlags/CountryFlags.cpp
- EU4toV2/Source/Mappers/CountryFlags/CountryFlags.h
- EU4toV2/Source/Mappers/CountryFlags/CountryFlagsMapping.cpp
- EU4toV2/Source/Mappers/CountryFlags/CountryFlagsMapping.h
- EU4toV2/Source/V2World/V2World.h
> updated mappings

- EU4ToVic2Tests/EU4ToVic2Tests.vcxproj
- EU4ToVic2Tests/EU4ToVic2Tests.vcxproj.filters
- EU4ToVic2Tests/EU4WorldTests/ColonialRegionTests/ColonialRegionTests.cpp
- EU4ToVic2Tests/EU4WorldTests/ColonialRegionTests/ColonialRegionsTests.cpp
- EU4ToVic2Tests/EU4WorldTests/CountryTests/EU4ActiveIdeasTests.cpp
- EU4ToVic2Tests/EU4WorldTests/CountryTests/EU4CountryFlagsTests.cpp
- EU4ToVic2Tests/EU4WorldTests/CountryTests/EU4CustomColorsTests.cpp
- EU4toV2/Source/EU4World/ColonialRegions/ColonialRegion.cpp
- EU4toV2/Source/EU4World/ColonialRegions/ColonialRegion.h
- EU4toV2/Source/EU4World/ColonialRegions/ColonialRegions.cpp
- EU4toV2/Source/EU4World/ColonialRegions/ColonialRegions.h
- EU4toV2/Source/EU4World/Country/EU4ActiveIdeas.cpp
- EU4toV2/Source/EU4World/Country/EU4ActiveIdeas.h
- EU4toV2/Source/EU4World/Country/EU4CountryFlags.cpp
- EU4toV2/Source/EU4World/Country/EU4CountryFlags.h
- EU4toV2/Source/EU4World/Country/EU4CustomColors.cpp
- EU4toV2/Source/EU4World/Country/EU4CustomColors.h
- EU4toV2/Source/Mappers/CountryMappings/CountryMappings.cpp
- EU4toV2/Source/Mappers/ProvinceMappings/ProvinceMapper.cpp
- EU4toV2/Source/Mappers/ProvinceMappings/ProvinceMapper.h
> Cleanup - Colonial regions mapper

- EU4ToVic2Tests/EU4ToVic2Tests.vcxproj
- EU4ToVic2Tests/EU4ToVic2Tests.vcxproj.filters
- EU4ToVic2Tests/EU4WorldTests/DiplomacyTests/EU4AgreementTests.cpp
- EU4ToVic2Tests/EU4WorldTests/DiplomacyTests/EU4DiplomacyTests.cpp
- EU4ToVic2Tests/EU4WorldTests/HistoryTests/CountryHistoryDateTests.cpp
- EU4ToVic2Tests/EU4WorldTests/HistoryTests/CountryHistoryTests.cpp
- EU4ToVic2Tests/EU4WorldTests/LocalisationTests/EU4LocalisationTests.cpp
- EU4toV2/Source/EU4World/Diplomacy/EU4Agreement.cpp
- EU4toV2/Source/EU4World/Diplomacy/EU4Agreement.h
- EU4toV2/Source/EU4World/Diplomacy/EU4Diplomacy.cpp
- EU4toV2/Source/EU4World/Diplomacy/EU4Diplomacy.h
- EU4toV2/Source/EU4World/History/CountryHistory.cpp
- EU4toV2/Source/EU4World/History/CountryHistory.h
- EU4toV2/Source/EU4World/History/CountryHistoryDate.cpp
- EU4toV2/Source/EU4World/History/CountryHistoryDate.h
- EU4toV2/Source/EU4World/Localisation/EU4Localisation.cpp
- EU4toV2/Source/EU4World/Localisation/EU4Localisation.h
- EU4toV2/Source/EU4World/World.cpp
- eu4diplomacy
- countryhistory
- eu4localisations
> Cleanup of eu4world internals

- EU4toV2/Data_Files/configurables/religion_map.txt
No need to create a new religion for them.
> Turumism mapping

- EU4toV2/Source/Mappers/ColonialTags/ColonialTag.cpp
- EU4toV2/Source/Mappers/CulturalUnions/CulturalUnion.cpp
Misplaced the code into registerKeys() instead of the constructors
> Fix for colonials & nationals

- EU4ToVic2Tests/EU4ToVic2Tests.vcxproj
- EU4ToVic2Tests/EU4ToVic2Tests.vcxproj.filters
- EU4ToVic2Tests/EU4WorldTests/CountryTests/EU4ActivePolicyTests.cpp
- EU4ToVic2Tests/MapperTests/PartyTypeMapper/PartyTypeTests.cpp
- EU4toV2/Data_Files/configurables/HPM/common/defines.lua
- EU4toV2/EU4ToV2.vcxproj
- EU4toV2/EU4ToV2.vcxproj.filters
- EU4toV2/Source/EU4World/Country/EU4ActivePolicy.cpp
- EU4toV2/Source/EU4World/Country/EU4ActivePolicy.h
- EU4toV2/Source/EU4World/Country/EU4Country.cpp
- EU4toV2/Source/EU4World/Country/EU4Country.h
- EU4toV2/Source/V2World/Country/Country.cpp
- EU4toV2/Source/V2World/Country/Country.h
- EU4toV2/Source/V2World/V2World.cpp
Simple national values conversion
> HPM national values

- EU4toV2/Data_Files/configurables/country_mappings.txt
Updated with cosmetic tags mappings
> Cosmetic tag mappings

- EU4toV2/Data_Files/configurables/culture_map.txt
Modded Taiwanese culture is already converted to Pinoy, so why not Polynesian culture in Formosa?
> Taiwanese Aboriginals become Pinoy

- EU4toV2/Data_Files/configurables/HPM/decisions/Baltic States.txt
- EU4toV2/Data_Files/configurables/HPM/decisions/Poland.txt
Prevent Zapadoslavia from forming Poland and PLC
> Prevent Polish-Lithuanian Commonwealth from forming the Baltic States

- EU4toV2/Data_Files/blankMod/output/decisions/NationalUnification.txt
- EU4toV2/Data_Files/configurables/HPM/decisions/NationalUnification.txt
- Fixed HPM cultural union formation to be easier and more intuitive. Also, countries now keep all their cores rather than losing them.
> Fixing Cultural Union Formation

- EU4toV2/Data_Files/blankMod/output/localisation/0_Names.csv
- EU4toV2/Data_Files/configurables/HPM/province_mappings.txt
- EU4toV2/Data_Files/configurables/province_mappings.txt
- Make 1-on-1 mapping for Ishenoca province
- Localize CHE as Cherokee instead of Cheyenne
> Ishenoca -> Baton Rouge

- EU4toV2/Data_Files/blankMod/output/events/CivilizationAndGunBoats.txt
- EU4toV2/Data_Files/blankMod/output/events/NationalValues.txt
- EU4toV2/Data_Files/blankMod/output/events/NationalistMovements.txt
- EU4toV2/Data_Files/blankMod/output/events/WorkPlaceEvents.txt
- EU4toV2/Data_Files/configurables/HPM/events/CBsAndCores.txt
- EU4toV2/Data_Files/configurables/HPM/events/CivilizationAndGunBoats.txt
- EU4toV2/Data_Files/configurables/HPM/events/CleanUp.txt
- EU4toV2/Data_Files/configurables/HPM/events/NationalValues.txt
- EU4toV2/Data_Files/configurables/HPM/events/NationalistMovements.txt
- EU4toV2/Data_Files/configurables/HPM/events/Noculture.txt
- EU4toV2/Data_Files/configurables/HPM/events/WorkPlaceEvents.txt
Block about a dozen events from popping up for AAA in order to reduce the amount of interruptions when running Observer mode
> Observer improvements

- EU4toV2/Data_Files/configurables/HPM/decisions/Italy.txt
- EU4toV2/Data_Files/configurables/country_mappings.txt
- EU4toV2/Data_Files/configurables/vn_province_mappings.txt
- croatian map tweaks
- Slovenian tag mapping addition
- dropped Italian irredenta
> Minor mapping tweaks

- EU4toV2/Data_Files/configurables/HPM/events/Revolution_Relations_Event.txt
Block some HPM Revolution relations events for the Observer tag
> Observer mode improvements

- EU4toV2/Data_Files/blankMod/output/decisions/converterProvinceRenaming.txt
- EU4toV2/Data_Files/blankMod/output/decisions/converterUnions.txt
- EU4toV2/Data_Files/blankMod/output/decisions/secondaryTags.txt
- EU4toV2/Data_Files/blankMod/output/events/nationalconverter.txt
- EU4toV2/Data_Files/configurables/HPM/decisions/converterPostCol.txt
- EU4toV2/Data_Files/configurables/HPM/decisions/converterProvinceRenaming.txt
- EU4toV2/Data_Files/configurables/HPM/decisions/converterUnions.txt
- EU4toV2/Data_Files/configurables/country_mappings.txt
Fixes based on Audax Validator reports
> Audax fixes 1

- EU4toV2/Source/EU4World/Provinces/EU4Province.cpp
- EU4toV2/Source/EU4World/Provinces/EU4Province.h
- EU4toV2/Source/EU4World/Provinces/ProvinceHistory.cpp
- EU4toV2/Source/EU4World/Provinces/ProvinceHistory.h
- EU4toV2/Source/Mappers/FlagColors/FlagColorMapper.cpp
- custom culture at start
- custom flag
> Fixes for custom nations

- EU4ToVic2/Source/EU4World/World.cpp
- EU4ToVic2/Source/EU4World/World.h
> Update revolution_target detection

- EU4ToVic2/Data_Files/blankMod/output/common/countries.txt
- EU4ToVic2/Data_Files/blankMod/output/common/countries/Repandia.txt
- EU4ToVic2/Data_Files/blankMod/output/events/Noculture.txt
- EU4ToVic2/Data_Files/blankMod/output/localisation/0_Cultures.csv
- EU4ToVic2/Data_Files/blankMod/output/localisation/0_Names.csv
- EU4ToVic2/Data_Files/configurables/HPM/events/Noculture.txt
- EU4ToVic2/Data_Files/configurables/culture_definitions.txt
- EU4ToVic2/Data_Files/configurables/culture_map.txt
- EU4ToVic2/Data_Files/configurables/culture_map_slaves.txt
- EU4ToVic2/Data_Files/configurables/dead_definitions.txt
- EU4ToVic2/Data_Files/configurables/nationals.txt
- EU4ToVic2/Data_Files/configurables/tech_groups.txt
> Add red panda culture

- EU4ToVic2/Data_Files/configurables/HPM/decisions/ACW.txt
- EU4ToVic2/Data_Files/configurables/HPM/decisions/NationalUnification.txt
- EU4ToVic2/Data_Files/configurables/HPM/decisions/converterPostCol.txt
- EU4ToVic2/Source/V2World/Decisions/HPMDecisions.cpp
* Fixes #1048 and related spams
> Clean out anything to do with DOM in decisions
