ParadoxGameConverters/EU4ToVic2

EU4toV2/Data_Files/cultureMap.txt, EU4toV2/Data_Files/slaveCultureMap.txt
It can be checked if the mappings themselves are newer or older, but the use of `v2` instead of `vic2` breaks the conversion.
=> Reverted Iohannes' version of culturemap and slaveculturemap which caused converter problems

EU4toV2/Source/V2World/V2Diplomacy.cpp
Good news!
- I finally got some version of boost to work with VS
- I'm capable of editing the source beyong adding "Hello World!" to log ;)
Before my change the agreements looked like this (and obviously were broken in Vicky):
> guarantee=
> {
> 	first="BYZ
> 	second="GEO
> 	start_date="1812.7.8
> 	end_date="1936.1.1"
> }
Now the quote signs after tags and start date exist.
=> history\diplomacy output fix

EU4toV2/EU4ToV2.vcxproj, EU4toV2/Source/EU4World/Provinces/EU4Province.cpp, EU4toV2/Source/EU4World/Provinces/EU4Province.h, EU4toV2/Source/V2World/V2Country.cpp, EU4toV2/Source/V2World/V2Diplomacy.cpp, EU4toV2/Source/V2World/V2Province.cpp, EU4toV2/Source/V2World/V2Province.h, EU4toV2/Source/V2World/V2World.cpp
- Added controllership conversion. Currently this only makes a difference in the country selection screen, because without wars and rebels converted, the game immediately removes controllership on campaign start.
- Added my boost dir to vcxproj
There are two edited parts which I'm particularly unsure about, marked them with a "TODO: ask Idhrendur" comment.
=> Province controllership is now converted 🎆

EU4toV2/Data_Files/cultureMap.txt, EU4toV2/Data_Files/slaveCultureMap.txt
Minor changes to culture conversion:
- Post-colonial cultures (e.g. Yankee, Amerikaner, ...) have been now split according to regions in the mapping code
- Slaves have been added for cultures without African diaspora so as to avoid the "noculture Slaves of Uzbekistan"
=> Minor additions

EU4toV2/Source/EU4World/World.cpp
Some mod,for example,game export from ck2,the country localization files are in the replace folder.
Before fix
After fix
=> converter not reading mod localisation in the replace folder

EU4toV2/CMakeLists.txt, EU4toV2/EU4ToV2.vcxproj, EU4toV2/Source/EU4World/EU4Country.cpp, EU4toV2/Source/EU4World/EU4Country.h, EU4toV2/Source/EU4World/Provinces/EU4Province.cpp, EU4toV2/Source/EU4World/Provinces/EU4Province.h, EU4toV2/Source/EU4World/World.cpp, EU4toV2/Source/EU4World/World.h
Add parsing of the map_area_data object in the EU4 savegame, which contains country-level state data; this enables provinces to expose whether they are in a state, and what their prosperity is.
Tested on a savegame from my latest megacampaign.
=> Clean parse states

EU4toV2/Source/EU4World/World.cpp
Converter would use current areas.txt to attempt map provinces from old save where they didn't exist and would crash. Now it will ignore those.
=> Fixed loading old saves with lacking provinces.

EU4toV2/Source/EU4World/Provinces/EU4Province.cpp, EU4toV2/Source/EU4World/Provinces/EU4Province.h, EU4toV2/Source/V2World/V2Province.cpp
I messed up with isColony assuming it returned isColony instead of wasColony. This will fix broken ex-colonies.
=> Fix to broken territorial handling (colony vs territorial province)

EU4toV2/Source/V2World/V2World.cpp, EU4toV2/Source/V2World/V2World.h
- code will now correctly replace the amount of great nations.
Tested a roman empire almost-wc with default 8 nations, game crashed on adapting history after selecting a country to play. After this fix with just 1 civilized nation it loads well:
=> Fix for #54

EU4toV2/Source/EU4World/Country/EU4CustomColors.cpp, EU4toV2/Source/EU4World/Country/EU4CustomColors.h, EU4toV2/Source/EU4World/Country/EU4NationalSymbol.cpp, EU4toV2/Source/EU4World/Country/EU4NationalSymbol.h, EU4toV2/Source/V2World/V2Flags.cpp
Paradox Special Naming System:
Blank flags and symbols are -1 in save.
Regular flags start at 2
Regular symbols start at 1
Why.
=> Fix for PSNS Flag ordering

EU4toV2/Source/EU4World/Army/EU4Army.cpp, EU4toV2/Source/EU4World/Army/EU4Army.h, EU4toV2/Source/V2World/V2Army.h
This PR does two things:
1. Fixes a bug by changing V2Army::getSourceArmy to return the EU4 object by reference, not copy. Without this, changes made to the source army, as for example by calling blockHomeProvince, do not persist; which causes an infinite loop in the case of unmatched provinces.
2. Optimises the home-province calculation by caching the provinces at army creation instead of re-iterating over the regiments every time.
Note that I have restored the old behaviour where a province is selected with a probability equal to the fraction of regiments that have that home province; the recent fix made all provinces equally probable by changing the local homeProvinces variable from a vector to a set. Let me know if that was deliberate, and I'll put it back.
=> Eu4army fix

EU4toV2/Source/Helpers/TechValues.cpp, EU4toV2/Source/Helpers/TechValues.h
Too few countries and in too obscure conditions would get higher tech levels - most notably access to mechanical_production - and this would deadlock entire economy until 1840s. On a test example two OPMs were only countries with high enough industry score to break 0.6 required for machine parts. Another example had a single 2-state country.
I've swapped normalized rankings for a score system where all civilized nations are linearly distributed across the range (and can share spots), so this will greatly increase tech diversity and tech availability.
Uncivilized nations are not affected.
=> Fixed tech ranking

EU4ToVic2Tests/ConfigurationTests.cpp, EU4toV2/Data_Files/Eu4ToVic2DefaultConfiguration.xml, EU4toV2/Source/Configuration.cpp, EU4toV2/Source/Configuration.h, EU4toV2/Source/EU4World/Country/EU4Country.cpp, EU4toV2/Source/V2World/Diplomacy/Diplomacy.cpp
Fix for #22
Liberty desire is a calculated value not stored in the save game. The "liberty_desire" in the save is a weird number which I believe is only generated through events and dissolves rapidly, and only factors in along with others (army comparison, opinion modifer etc.) when calculating the final score.
Thus, going through relationship attitude as we currently do is the correct path, although only values that actually exist for colonies are "loyal", "disloyal" or "rebellious", so the options result in 5, 90 and 95.
There's not much we can do about this, but additional converter option will simplify the selection for players. There is no need to deceive players entering "62" into liberty desire thinking their Brazil sitting at 63 will be excluded from integration, since our values …
=> Absorption

EU4toV2/Source/Configuration.h, EU4toV2/Source/EU4World/Provinces/ProvinceHistory.cpp, EU4toV2/Source/V2World/Country/Country.cpp
No reduction at 1836, 15%  at 1821, 50% 1750, and then it slowly degrades to 20% at 1490 and 15% at 1356.
=> Lower literacy for earlier conversion dates.

EU4toV2/Data_Files/Eu4ToVic2DefaultConfiguration.xml, EU4toV2/Data_Files/configurables/starting_factories.txt, EU4toV2/Source/EU4World/Army/EU4Regiment.h, EU4toV2/Source/EU4World/Country/EU4Country.cpp, EU4toV2/Source/EU4World/Country/EU4Country.h, EU4toV2/Source/EU4World/World.cpp, EU4toV2/Source/EU4World/World.h, EU4toV2/Source/Mappers/UnitTypes/UnitTypeMapper.cpp, EU4toV2/Source/Mappers/UnitTypes/UnitTypeMapper.h, EU4toV2/Source/V2World/V2World.cpp
- Puppets now transfer half their manufactories to overlord for purposes of starting industry weight and factory distribution.
- effects of being ahead or behind with admin tech on industry are now multiplied by 5 as previous values did next to nothing.
- manufactory weight is multiplied by manufactory density to better represent industrialization centers.
- Starting factory counts have been updated to exactly match vanilla.
Unrelated:
- unit type mapper inited too early, not grabbing mod unit definitions.
=> Industrialization review

EU4toV2/Source/EU4World/Country/Countries.cpp
We weren't catching alpha-alpha-digit, which apparently some mods use.
=> Expanding countries catch regex

EU4toV2/Source/EU4World/Country/EU4Country.cpp, EU4toV2/Source/EU4World/Country/EU4Country.h, EU4toV2/Source/EU4World/History/CountryHistory.cpp, EU4toV2/Source/EU4World/History/CountryHistory.h, EU4toV2/Source/EU4World/World.cpp, EU4toV2/Source/V2World/V2World.cpp
Seems like a PDX oversight. Formables don't have primary_culture or religion keys.
=> Fix to save losing primary culture/religion on country formation.

EU4toV2/Data_Files/configurables/province_mappings.txt
1.25 mappings were copied over.
=> fixed 1.24 mappings

EU4toV2/Source/EU4World/Country/EU4Country.cpp
Vic2 cannot read filenames with non-base-ascii characters in them, so base country names need to conform.
=> Fix for non-ascii names

EU4toV2/Data_Files/blankMod/output/events/converterEvents.txt, EU4toV2/Data_Files/configurables/unions.txt
As Vic2 Arabia doesn't have cultural cores lingering around, neither shall we.
Otherwise, Saudi Arabia would feel entitled to conquer everything from Gibraltar to Sudan.
Also fixed the Caliphate to get cores everywhere they control a Mosque.
=> Removing Arab culture-cores

EU4ToVic2Tests/EU4ToVic2Tests.vcxproj, EU4ToVic2Tests/EU4ToVic2Tests.vcxproj.filters, EU4ToVic2Tests/MapperTests/CountryMappings/CountryMappingTests.cpp, EU4toV2/Data_Files/configurables/country_mappings.txt, EU4toV2/Data_Files/configurables/culture_map_slaves.txt, EU4toV2/Source/Mappers/CountryMappings/CountryMapping.cpp, EU4toV2/Source/Mappers/CountryMappings/CountryMappings.cpp
Fixes #524 - allows mapping to target tag without a source tag, instead relying on only reforms/flags.
=> Wildcard tagmapper

EU4ToVic2Tests/EU4WorldTests/RelationTests/EU4EmpireTests.cpp, EU4toV2/Data_Files/blankMod/output/decisions/converterUnions.txt, EU4toV2/Source/EU4World/Relations/EU4Empire.cpp, EU4toV2/Source/EU4World/Relations/EU4Empire.h, EU4toV2/Source/EU4World/World.cpp, EU4toV2/Source/EU4World/World.h, EU4toV2/Source/Mappers/CultureGroups/CultureGroup.h, EU4toV2/Source/V2World/Country/Country.h, EU4toV2/Source/V2World/Diplomacy/Diplomacy.cpp, EU4toV2/Source/V2World/Diplomacy/Diplomacy.h, EU4toV2/Source/V2World/Output/outProvince.cpp, EU4toV2/Source/V2World/Province/Province.cpp, EU4toV2/Source/V2World/Province/Province.h, EU4toV2/Source/V2World/V2World.cpp, EU4toV2/Source/V2World/V2World.h
Removes Germany and Holy Roman Empire (country) in case the HRE enacted all decentralization reforms
- remove German cores from all provinces - disables forming Germany
- remove HRE cores from all provinces - disables HRE Nationalists
- disable centralize_hre decision when no HRE core in capital - disables forming HRE
- remove GER as a cultural union for germanic culture group - disables German Pan-Nationalists
- sphere HRE members to Emperor and grant military access through their territory
=> Decentralized HRE

EU4toV2/Source/Mappers/ProvinceDetails/ProvinceDetailsMapper.cpp
For some reason the game gets stuck at "Adapting History" when `coral_island` terrain is assigned to some Pacific islands. Until it's solved, coral_island is removed from province history.
=> HPM coral_island patch

EU4toV2/Data_Files/blankMod/output/decisions/ACW.txt
Restricts applying to US statehood only to US states in the same culture group as the in-world USA. E.g. a French Texas would join a French USA, but an English Texas would not. This way the US won't just diplomatically grab the rest of the modern US while having no historical in-world claim to it.
=> Updates to Apply to US Statehood

EU4toV2/Data_Files/blankMod/output/decisions/converterUnions.txt
In EU IV 1.31, Fiji, Samoa, and Hawaii start as colonized provinces that have nations which can conquer or be conquered, it doesn't make sense anymore to have these provinces suddenly change owners to their historical counterparts in Victoria II. 
A Maori Empire in New Zealand which unites Polynesia in EU IV, for example, would suddenly loose 3 of it's islands in Victoria II for no apparent reason; now instead with these changes, those nations would just get cores on the islands while still being owned by the Maori Empire
=> Fiji, Samoa, and Hawaii Province Ceding

EU4toV2/Data_Files/configurables/culture_map.txt
The Picts were a Brythonic-Speaking people that historically were assimilated around 800 AD, it doesn't make sense to convert EU IV Gaelic-speaking Highland Scottish provinces into Pictish pops and suddenly revive the long-dead culture. It makes more sense to map the highland Scots as Scottish pops or their own culture
=> Remapped Highland Scottish from Pictish

EU4toV2/Source/Configuration.cpp, EU4toV2/Source/Configuration.h, EU4toV2/Source/V2World/Province/ProvinceNameParser.cpp
Used for naming regiments. Importing HPM province localization isn't enough, because the mod makes only localizations for provinces it renames, the rest is loaded from Vanilla.
=> Import Vanilla province localization for hybridization

EU4toV2/Data_Files/configurables/country_mappings.txt, EU4toV2/Data_Files/configurables/vn_province_mappings.txt, EU4toV2/Source/V2World/V2World.cpp
- dead country cores will now be retained or deleted on Vic2 side as well, according to configuration option
- fixed some slovene mappings
- ASE now maps to england, not GBR to prevent collision.
=> Fixing transitional core retention for dying nations.

EU4toV2/Data_Files/blankMod/output/events/shattered_hre.txt
Lack of any_province scope in Vic2 must be the biggest oversight in any Paradox game
=> Fix HRE core removal event

EU4ToVic2/Data_Files/blankMod/output/common/countries.txt
Cores are added via nationals.txt, but we never added country definition
=> Add Mongol Khanate tag (KHA)
